[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "ezCOS"
version = "0.1.0"
description = "Outil de simplification de la gestion des COS."
readme = "Readme.md"
authors = [
    { name = "Géry Casiez", email = "gery.casiez@univ-lille.fr" },
]

requires-python = ">=3.0"

classifiers = [
    "Programming Language :: Python :: 3",
]

dependencies = [
    "odysseeapi",
    "openpyxl",
    "argparse",
    "configparser",
    "pandas",
    "pymupdf",
    "unidecode"
]

[project.urls]
Homepage = "https://github.com/casiez/ezCOS"

[project.scripts]
ezCOS = "ezCOS.ezCOS:main"

[tool.setuptools.packages.find]
exclude = ["templates", "carbone"]

